
- name: install apache2 server
  apt:
    name: apache2
    state: present

- name: install mysql server
  apt:
    name: mysql-server
    state: present

- name: install php
  apt:
    name: php
    state: present

- name: start apache2 service
  service:
    name: apache2
    state: started
    enabled: yes

- name: start mysql service
  service:
    name: mysql
    state: started
    enabled: yes

- name: configure apache
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
  notify: restart apache2    

- name: allow ports 53
  community.general.ufw:
    rule: allow
    port: '53'
- name: allow ports 443
  community.general.ufw:
    rule: allow
    port: '443'